version: '3'
services:
  rails:
    build: .
    depends_on:
      - db
    command: ./bin/run-dev.sh
    volumes:
      - .:/app:Z
      - /app/node_modules # Anonymous volume, isolates node_modules folder from the host filesystem
    ports:
      - "3000:3000"
  db:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data
    #ports:
      #- "5432:5432"

volumes:
  pgdata:
