name: Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker images
        run: docker-compose build
      - name: Initialize database
        run: docker-compose run rails bin/initialize.sh
      - name: Run tests
        run: docker-compose run rails bin/test.sh
